[pytest]
testpaths = tests
python_files = test_*.py
addopts = -v --html=reports/report.html --self-contained-html --alluredir=reports/allure-results --base-url https://192.168.3.56
markers =
    smoke: 冒烟测试
    yunwei: 运维资产相关测试
